# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='new post', max_length=240),
        ),
    ]
