# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'postHa', 'verbose_name_plural': 'addPost'},
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('send', 'Send')], default='draft', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='new post', max_length=240, verbose_name='post title'),
        ),
    ]
