# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170321_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='new post', max_length=240, unique=True, verbose_name='post title'),
        ),
    ]
