# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_post_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[web.models.auther_email]),
        ),
    ]
