# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170321_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[web.validators.auther_email]),
        ),
    ]
